import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter, Vazirmatn } from "next/font/google";

// provider
import { auth } from "@/lib/auth";
import { TrpcProvider } from "@/components/providers/index";
import { Toaster } from "@/components/ui/toaster";

const fontSans = Inter({
   subsets: ["latin"],
   variable: "--font-sans",
});
const fontVazir = Vazirmatn({
   subsets: ["latin"],
   variable: "--font-vazir",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   const session = await auth();

   return (
      <TrpcProvider session={session}>
         <html lang="en" className="dark">
            <body
               className={cn(
                  "min-h-screen max-w-screen-xl mx-auto px-10 font-vazir",
                  fontSans.variable,
                  fontVazir.variable
               )}
            >
               {children}
               <div dir="rtl">
                  <Toaster />
               </div>
            </body>
         </html>
      </TrpcProvider>
   );
}
