import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// provider
import { TrpcProvider } from "@/components/providers/index";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   const session = await auth();

   return (
      <TrpcProvider session={session}>
         <html lang="en">
            <body>{children}</body>
         </html>
      </TrpcProvider>
   );
}
